#!/bin/sh

# check_sentry - a nagios plugin for checking if sentry is active
# by Matt Simerson
# 2013-12-10 - initial writing
# 2026-02-10 - extended for bash version

# INSTRUCTIONS
# install this script in your nagios libexec dir (check nrpe.cfg)
#  fetch -o /usr/local/libexec/nagios/check_sentry https://raw.githubusercontent.com/msimerson/sentry/master/check_sentry
#
# add a line like this nrpe.cfg:
#    command[check_sentry]=/usr/local/libexec/nagios/check_sentry
#
# and restart nrpe:
#    service nrpe restart
#
# install this script in your nagios libexec dir (check nrpe.cfg)

SENTRY_DIR=/var/db/sentry
SENTRY_BIN_PL="$SENTRY_DIR/sentry.pl"
SENTRY_BIN_SH="$SENTRY_DIR/sentry"
GREP=/usr/bin/grep

if [ ! -x $GREP ]; then
    echo "ERROR: edit check_sentry and set GREP"
    GREP="grep"
fi

echoerr() { echo "$@" >&2; }
usage() {
    echo "   usage: $0"
    echo " "
    exit 3
}

$GREP -v '^#' /etc/hosts.allow | $GREP -q sentry
if [ $? -ne 0 ]; then
    echo "sentry not active in hosts.allow!"
    exit 2
fi

# Check for either bash or perl version
if [ -x "$SENTRY_BIN_SH" ]; then
    echo "OK - sentry (bash) installed and active"
    exit 0
fi

if [ -x "$SENTRY_BIN_PL" ]; then
    echo "OK - sentry (perl) installed and active"
    exit 0
fi

echoerr "sentry not executable by $USER!"
if [ ! -d $SENTRY_DIR ]; then
    echo "sentry dir ($SENTRY_DIR) doesn't exist!"
    exit 2
fi

echo "OK - sentry appears installed and active"
exit 0
